export const UPDATE_INPUT_TEXT = 'UPDATE_INPUT_TEXT';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';

export const AWAITING_SEARCH_RESULTS = 'AWAITING_SEARCH_RESULTS';
export const SEARCH_RESULTS_RECEIVED = 'SEARCH_RESULTS_RECEIVED';

export const RESET_IMAGES = 'RESET_IMAGES';
export const ADD_IMAGES = 'ADD_IMAGES';
export const UPDATE_NUM_PAGES = 'UPDATE_NUM_PAGES';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const UPDATE_MODAL_INDEX = 'UPDATE_MODAL_INDEX';

export const FETCH_SEARCH_HISTORY = 'FETCH_SEARCH_HISTORY';

export const UPDATE_ERROR = 'UPDATE_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
